### PR TITLE
login / register design

### PR DESCRIPTION
**Pull request by TomRomeo**
This pr aims to implement the necessary frontend and backend design for a successful login and registration process

### CODE REVIEW

**Comment by TomRomeo** [comment]
# Current state of the login and registration views
This is the current implementation of the login and register views under the /login path. Any feedback? :)
### Login view
Login view
### Register view
Register view

**Review by memeToasty — APPROVED** [review]
👍

**Review by 4KevR — APPROVED** [review]
We definitely have to work on a color scheme, but the implementation looks good.

**Review by Julian702 — APPROVED** [review]
still a lot of work to do here

**Pull request merged**
