### PR TITLE
Remove e-mail logging

### LINKED ISSUE #237: Remove e-mail address logging
## Description

Currently, we are logging E-Mail addresses in the user service, which is against a lot of policies, so let's not do that.

### PR DESCRIPTION
**Pull request by memeToasty**
# Description

This PR removes logging of emails in the user service, as well mutes the GORM logger.
This may lead to the fact that our tracing architecture may have consequences, but this is definitely a step towards compliance.

## Resolved Issues

resolves #237

### CODE REVIEW

**Review by Julian702 — APPROVED** [review]

**Comment by memeToasty** [comment]
This needs more work, as I just discovered that still e-mails can end up in the logs...

**Comment by Julian702** [comment]
Please rename your branch according to our contribution guidelines. Please also refrain from opening unnecessarily many prs. An unsigned commit can be fixed without closing the pr.

**Comment by memeToasty** [comment]
> Please rename your branch according to our contribution guidelines.

As far as I am aware, we do not have any contribution guidelines in main as far as I am aware.
I am sorry that the name of the branch offends you.

I will ask you for your help in future PRs! I am so sorry

> Please also refrain from opening unnecessarily many prs. An unsigned commit can be fixed without closing the pr.

I did not want to do any force pushes on the branch, as I have been scolded for that in the past as well. I am sorry!
Will not happen again😭

I hope you can forgive my sins👉👈🥺

**Comment by memeToasty** [comment]
> This needs more work, as I just discovered that still e-mails can end up in the logs...

I have now tested this locally and I cannot reproduce this issue, maybe I forgot to build the change when writing this comment

**Review by Julian702 — APPROVED** [review]

**Review by TomRomeo — CHANGES_REQUESTED** [review]
Instead of removing all logging lines, I'd suggest to only remove the printed email while keeping the static text for log tracability.

**Comment by memeToasty** [comment]
> Instead of removing all logging lines, I'd suggest to only remove the printed email while keeping the static text for log tracability.

I get where you are coming from, but I don't think that this logging statement adds any value to the logs.
In regards to traceability, those function calls still get registered by our tracing stack

**Comment by TomRomeo** [comment]
> > Instead of removing all logging lines, I'd suggest to only remove the printed email while keeping the static text for log tracability.
> 
> I get where you are coming from, but I don't think that this logging statement adds any value to the logs. In regards to traceability, those function calls still get registered by our tracing stack

Maybe the others can also state their opinion but since every other backend function has these logging statements, I would prefer to have them here as well. I personally also use these logging lines as indications for the program flow when debugging.

**Comment by memeToasty** [comment]
> > > Instead of removing all logging lines, I'd suggest to only remove the printed email while keeping the static text for log tracability.
> > 
> > 
> > I get where you are coming from, but I don't think that this logging statement adds any value to the logs. In regards to traceability, those function calls still get registered by our tracing stack
> 
> Maybe the others can also state their opinion but since every other backend function has these logging statements, I would prefer to have them here as well. I personally also use these logging lines as indications for the program flow when debugging.

Fair point, I will add it back in!

**Review by TomRomeo — APPROVED** [review]
❤️

**Pull request merged**
